##서버 포트 설정
#server.port=8000
#
##인코딩 UTF-8설정
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true
#server.servlet.encoding.force-request=true
#server.servlet.encoding.force-response=true
#server.tomcat.uri-encoding=UTF-8
#
##뷰리졸버 설정
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/springboot_jaehyeon?useUnicode=true&serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: root
    password: toor
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 421835711385-1m385181f86graanp23kbqpku1mm4q6f.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          
mybatis:
  mapper-locations:
  - /mappers/*.xml
    
    
    
    
    
    
    